import operator
from typing import Annotated, List, TypedDict
from pydantic import BaseModel, Field

# 1. This is the global State that flows through the graph
class AuditorState(TypedDict):
    """The shared memory for the Autonomous Regulatory Auditor."""
    
    # The original user query (e.g., 'Solar IoT Sensor')
    query: str
    
    # The 'operator.add' reducer is the secret sauce. 
    # It tells LangGraph to APPEND new list items instead of overwriting.
    worker_results: Annotated[List[str], operator.add]
    
    # The specific search axes generated by the Supervisor
    sub_tasks: List[str]
    
    # The final answer produced by the Aggregator
    final_hscode: str
    final_confidence: str
    
    # Optional: Track how many steps have been taken for the 60s limit
    step_count: Annotated[int, operator.add]

    # Auditor metrics
    faithfulness_score: float
    status: str
    critique: str
    total_tokens: int
    retrieval_context: Annotated[List[str], operator.add]

# 2. This is the schema for the Worker's private input
# When using the 'Send' API, each worker only gets a slice of the state.
class WorkerInput(TypedDict):
    query: str # This will be the specific axis like 'Solar components'